from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .storage import atomic_write_text


def candidate_issues(
    finding: dict[str, Any], issues: list[dict[str, Any]], limit: int = 8
) -> list[dict[str, Any]]:
    finding_fingerprints = set(finding.get("fingerprints", []))
    finding_tokens = _tokens(
        " ".join(
            str(finding.get(key, "")) for key in ("title", "category", "claim", "affected_paths")
        )
    )
    scored = []
    for issue in issues:
        issue_fingerprints = set(issue.get("fingerprints", []))
        exact = len(finding_fingerprints & issue_fingerprints)
        issue_tokens = _tokens(
            " ".join(
                str(issue.get(key, ""))
                for key in ("title", "category", "summary", "affected_paths")
            )
        )
        overlap = len(finding_tokens & issue_tokens) / max(len(finding_tokens | issue_tokens), 1)
        same_category = finding.get("category") == issue.get("category")
        score = exact * 100 + overlap * 10 + (2 if same_category else 0)
        if score > 0.5:
            scored.append((score, issue))
    return [issue for _, issue in sorted(scored, key=lambda item: item[0], reverse=True)[:limit]]


def apply_decision(
    issues: list[dict[str, Any]],
    decision: dict[str, Any],
    finding: dict[str, Any],
    task_id: str,
) -> str | None:
    action = str(decision.get("decision", "")).upper()
    now = datetime.now(timezone.utc).isoformat()
    if action == "ADD":
        issue = decision.get("issue")
        if not isinstance(issue, dict):
            raise ValueError("ADD decision requires an issue object")
        next_number = max(
            [int(match.group(1)) for item in issues if (match := re.match(r"ISSUE-(\d+)$", item["id"]))]
            or [0]
        ) + 1
        issue = dict(issue)
        issue.update(
            {
                "id": f"ISSUE-{next_number:04d}",
                "status": "open",
                "source_tasks": [task_id],
                "created_at": now,
                "updated_at": now,
            }
        )
        issues.append(issue)
        return issue["id"]
    if action == "MERGE":
        target = decision.get("target_issue_id")
        issue = next((item for item in issues if item["id"] == target), None)
        if issue is None:
            raise ValueError(f"MERGE target does not exist: {target}")
        for field in ("fingerprints", "affected_paths", "source_tasks"):
            additions = [task_id] if field == "source_tasks" else finding.get(field, [])
            issue[field] = sorted(set(issue.get(field, [])) | set(additions))
        existing_evidence = issue.setdefault("evidence", [])
        for evidence in finding.get("evidence", []):
            if evidence not in existing_evidence:
                existing_evidence.append(evidence)
        issue["updated_at"] = now
        return str(target)
    if action in {"DISREGARD", "INCONCLUSIVE"}:
        return None
    raise ValueError(f"unknown manager decision {action!r}")


def render_markdown(issues: list[dict[str, Any]], path: Path) -> None:
    ordered = sorted(issues, key=lambda item: (item.get("priority", "P9"), item["id"]))
    lines = [
        "# Data Issues — Agentic Audit",
        "",
        "> Generated from `audit/issues.json`. Do not edit this file directly.",
        "",
        f"Open issues: {sum(item.get('status') == 'open' for item in ordered)}",
        "",
    ]
    if not ordered:
        lines.extend(["No issues have been accepted yet.", ""])
    for issue in ordered:
        lines.extend(
            [
                f"## {issue['id']} [{issue.get('priority', 'P?')}] {issue.get('title', 'Untitled issue')}",
                "",
                f"- **Status:** {issue.get('status', 'open')}",
                f"- **Category:** {issue.get('category', 'unspecified')}",
                f"- **Source tasks:** {', '.join(issue.get('source_tasks', [])) or 'unknown'}",
                f"- **Affected paths:** {', '.join(issue.get('affected_paths', [])) or 'not localized'}",
                "",
                str(issue.get("summary", "")),
                "",
                f"**Why it matters:** {issue.get('why_it_matters', '')}",
                "",
                f"**Smallest credible remedy:** {issue.get('smallest_remedy', '')}",
                "",
                "### Evidence",
                "",
            ]
        )
        for evidence in issue.get("evidence", []):
            if isinstance(evidence, dict):
                source = evidence.get("source", "evidence")
                locator = evidence.get("locator", "")
                observation = evidence.get("observation", evidence)
                lines.append(f"- `{source}{':' + str(locator) if locator else ''}` — {observation}")
            else:
                lines.append(f"- {evidence}")
        if not issue.get("evidence"):
            lines.append("- No structured evidence recorded.")
        lines.append("")
    atomic_write_text(path, "\n".join(lines))


def _tokens(value: str) -> set[str]:
    return {token for token in re.findall(r"[a-z0-9_./-]+", value.lower()) if len(token) > 2}
